bibtex UpScalingDEMSimulations_doublesidedprint
pdflatex UpScalingDEMSimulations_doublesidedprint
makeglossaries UpScalingDEMSimulations_doublesidedprint
pdflatex UpScalingDEMSimulations_doublesidedprint
bibtex UpScalingDEMSimulations_electronic
pdflatex UpScalingDEMSimulations_electronic
makeglossaries UpScalingDEMSimulations_electronic
pdflatex UpScalingDEMSimulations_electronic
